<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Tienda Retablo | Registrate</title>
	<!-- bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
<!-- 	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> -->
	<link rel="stylesheet" href="<?php echo BASE_URL?>public/assets/css/styles.css"/>
</head>
<body>
	<aside>
		<div style="text-align: center">
			<img alt="Logo" src="<?php echo BASE_URL?>public/assets/images/logoSolo3.svg"/ width="60px">	
		</div>
	  <h1> HUACHO DELIVERY </h1>
	    <nav>
	      <ul>
	        <li><a href="#nowhere" title="IR A Tragos">Tragos</a></li>
	        <li><a href="#nowhere" title="IR A Piqueos">Piqueos</a></li>
	      </ul>
	    </nav>
	    <p class="footer">Powered By GManriqe</p>
	</aside>

	<a id="nav-toggle" href="#!" class="position"><span></span></a>
	<main>
	  <header>
	    <div class="container">
	    	<div class="row">
	    		<div class="col-xs-6 col-xs-offset-3">
	    			<a href="<?php echo BASE_URL?>"><img alt="Logo" src="<?php echo BASE_URL?>public/assets/images/logoPrincipal.svg"></a>
	    		</div>
	    	</div>
	    </div>
	  </header> <!-- fin header -->
	  <div>
	  </div> <!-- fin  -->
	 <section class="container-login" style="padding: 30px">
	 	<div class="container">
	 		<div class="row">
<!-- 	 			<div class="col-md-6 col-md-offset-3"> -->
<!-- 	 				<p><i class="fa fa-arrow-circle-left" aria-hidden="true"></i></p> -->
<!-- 	 			</div> -->
	 			<div class="col-md-6 col-md-offset-3">
	 				<!-- <form action="<?php echo BASE_URL?>usuario/registerus" method="POST"> -->
	 				<form method="POST" id="form_signin">
	 					<div class="form-group">
	 						<label>Nombre</label>
	 						<input type="text" class="form-control" name="nombre" id="nombre"/>
	 					</div>
	 					<div class="form-group">
	 						<label>Usuario</label>
	 						<input type="text" class="form-control" name="usuario" id="usuario"/>
	 					</div>
	 					<div class="form-group">
	 						<label>Contraseña</label>
	 						<input type="text" class="form-control" name="clave1" id="clave1"/>
	 					</div>
	 					<div class="form-group">
	 						<label>Repita contraseña</label>
	 						<input type="text" class="form-control" name="clave2" id="clave2"/>
	 					</div>
	 					<div class="form-group">
	 						<label>Email</label>
	 						<input type="email" class="form-control" name="email" id="email"/>
	 					</div>
	 					<div class="form-group">
	 						<label>Telefono</label>
	 						<input type="text" class="form-control" name="telefono" id="telefono"/>
	 					</div>
	 					<div class="form-group text-center">
	 						<!-- <button type="submit" class="btn yellow">Registrar</button> -->
	 						<button type="button" id="btn_registrar" class="btn yellow">Registrar</button>
	 					</div>
	 					<div id="zona_respuesta"></div>
	 				</form>
	 			</div>
	 		</div>
	 	</div>
	 </section>
	<section class="container-contactus">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="contactacus">
						<p>Llegamos en menos de 20 minutos -<strong> TODO HUACHO</strong></p>
						<a href="">CONTACTANOS</a>
					</div>
				</div>
			</div>
		</div>
	</section>
	</main>
		<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
		<script type="text/javascript">
			$(document).ready(function(){
			  $('#nav-toggle').click(function() {
			    //icon
			    $(this).toggleClass('active');
			    
			    if ($('body').hasClass('show-nav')) {
			      // Hide sidebar
			      $('body').removeClass('show-nav');
			    } else { 
			      // If sidebar is hidden:
			      $('body').addClass('show-nav'); // Display sidebar
			    }
			  });
			});
		</script>
		<?php if(isset($_layoutParams['js']) && count($_layoutParams['js'])): ?>
			<?php foreach($_layoutParams['js'] as $layout): ?>
   				<script src="<?php echo  $layout ?>" type="text/javascript"></script>
			<?php endforeach; ?>
		<?php endif; ?> 
	</body>
	</html>