<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Tienda Retablo | Lista Productos</title>
	<!-- bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
	<link href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css">
	<link rel="stylesheet" href="<?php echo BASE_URL?>public/assets/css/styles.css"/>
</head>
<body>
	<aside>
		<div style="text-align: center">
			<img alt="Logo" src="<?php echo BASE_URL?>public/assets/images/logoSolo3.svg"/ width="60px">	
		</div>
	  <h1> HUACHO DELIVERY </h1>
	    <nav>
	      <ul>
	        <li><a href="#nowhere" title="IR A Tragos">Tragos</a></li>
	        <li><a href="#nowhere" title="IR A Piqueos">Piqueos</a></li>
	      </ul>
	    </nav>
	    <p class="footer">Powered By GManriqe</p>
	</aside>
	<a class="login" href="<?php echo BASE_URL?>index/iniciasesion">SA</a>
	<a id="nav-toggle" href="#!" class="position"><span></span></a>
	<main>
	  <header>
	    <div class="container">
	    	<div class="row">
	    		<div class="col-xs-6 col-xs-offset-3">
	    			<a href="<?php echo BASE_URL?>"><img alt="Logo" src="<?php echo BASE_URL?>public/assets/images/logoPrincipal.svg"></a>
	    		</div>
	    	</div>
	    </div>
	  </header> <!-- fin header -->
	  <div>
	  </div> <!-- fin  -->
	 <section class="container-loginsa" style="padding: 30px">
	 	<div class="container">
	 		<div class="row">
	 			<div class="col-md-12">
					<!-- datatable -->
	 				<div class="panel panel-default">
					<div class="panel-heading">
						<a class="btn btn-primary" href="<?php echo BASE_URL?>producto/addusuario">Nuevo Producto</a>
					</div>
					<div class="panel-body">
						<div class="table-responsive">
							<table id="myTable" class="table table-striped table-bordered table-hover "
								id="dataTables-usuarios">
								<thead>
									<tr>
										<th><?php echo _('Codigo Producto')?></th>
										<th><?php echo _('Nombre Producto')?></th>
										<th><?php echo _('Precio Producto')?></th>
										<th><?php echo _('Stock')?></th>
										<th><?php echo _('Fecha Registro')?></th>
										<th></th>
									</tr>
								</thead>
								<tbody id="body_usuarios">
									<?php while($producto = $this->productos->fetch_object()):?>
									 <tr>
									 	<td><?php echo $producto->codigoproducto?></td>
										<td><?php echo $producto->nombre?></td>
										<td><?php echo $producto->precio?></td>
										<td><?php echo $producto->stock?></td>
										<td><?php echo $producto->fechareg?></td>
										
										<td>
											<a href="<?php echo BASE_URL?>producto/formEditar/<?php echo $producto-> codigoproducto?>">editar</a> |
											<a href="<?php echo BASE_URL?>producto/eliminar/<?php echo $producto-> codigoproducto?>">eliminar</a>
										</td>
									 </tr>
									<?php endwhile;?>
								</tbody>
							</table>
						</div>
					</div>
				</div>
	 			<!-- fin datatable -->	
	 			</div>
	 		</div>
	 	</div>
	 </section>
	</main>
		<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
		<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
		<script type="text/javascript">
			$(document).ready(function(){
			  $('#nav-toggle').click(function() {
			    //icon
			    $(this).toggleClass('active');
			    
			    if ($('body').hasClass('show-nav')) {
			      // Hide sidebar
			      $('body').removeClass('show-nav');
			    } else { 
			      // If sidebar is hidden:
			      $('body').addClass('show-nav'); // Display sidebar
			    }
			  });
			});

			$(document).ready(function(){
				$('#myTable').DataTable();
			});
		</script>
		
	</body>
	</html>